### ISSUE TITLE
Readme Instruction Error : pip install -r requirements-actions.txt 

### ISSUE THREAD

**Issue by blestab** [RasaHQ/rasa-for-beginners#1]
error when trying to follow a step from the readme to install dependencies for the actions server

```
C:\my\projects>git clone https://github.com/RasaHQ/rasa-for-beginners.git
Cloning into 'rasa-for-beginners'...
remote: Enumerating objects: 117, done.
remote: Counting objects: 100% (117/117), done.
remote: Compressing objects: 100% (57/57), done.
remote: Total 117 (delta 57), reused 117 (delta 57), pack-reused 0
Receiving objects: 100% (117/117), 376.04 KiB | 197.00 KiB/s, done.
Resolving deltas: 100% (57/57), done.

C:\my\projects>cd rasa-for-beginners

C:\my\projects\rasa-for-beginners>pip install -r requirements-actions.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements-actions.txt'

C:\my\projects\rasa-for-beginners>
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @tabergma will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by karen-white** [comment]
@blestab Looks like the file was accidentally omitted from the repo - thank you for catching that. I've added the requirements file here: https://github.com/RasaHQ/rasa-for-beginners/blob/master/requirements-actions.txt

Let us know if you run into any other issues
